### ISSUE TITLE
Include in thumbor wiki?

### ISSUE THREAD

**Issue by heynemann** [rebuy-de/thumbor-s3#1]
If this library is meant to be used by thumbor's users do you think you could add it to our [plug-ins page](https://github.com/thumbor/thumbor/wiki/Plugins)?

**Comment by heynemann** [comment]
Btw, thanks for helping improve thumbor's community!

**Comment by bjoernhaeuser** [comment]
@heynemann I will, but only after I added some tests and made it battle proof :)

**Comment by bjoernhaeuser** [comment]
@heynemann are you interested in looking into #2? After that I would love to add to the page!

**Comment by bjoernhaeuser** [comment]
Done! https://github.com/thumbor/thumbor/wiki/Plugins#thumbor_s3
